volumes:
  dados:

networks:
  database_network:
  web_network:
  queue_network:

services:

  database:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=123qwe
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_network

    
  frontend:
    image: nginx:1.27
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf #configuração do proxy reverso
    ports:
      - 81:81
    networks:
      - web_network
    depends_on:
      - app
    
  app:
    image: python:3.12
    volumes:
      - ./app:/app
    working_dir: /app
    command: ./app.sh
    networks:
      - database_network
      - web_network
      - queue_network
    environment:
      - DB_NAME=cadastro_cliente
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=123qwe
      - REDIS_HOST=queue
    depends_on:
      - database
  
  queue:
    image: redis:7.4
    environment:
      - REDIS_HOST=queue
    networks:
      - queue_network
  
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /worker
    command: worker.py
    networks:
      - queue_network
    depends_on:
      - queue